#!/bin/sh
# Gradle start up script for POSIX generated by Gradle.
set -e
APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$CLASSPATH" ]; then
  echo "gradle-wrapper.jar 가 없습니다. IntelliJ로 프로젝트를 열면 자동 생성되며,"
  echo "또는 로컬에 gradle 설치 후 'gradle wrapper --gradle-version 8.10.2' 를 실행하세요." >&2
  exit 1
fi
if [ -n "$JAVA_HOME" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi
exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
